<MainPage>:
    MDBoxLayout:
        orientation:'vertical'
        MDTopAppBar:
            id:tbar
            title:"bhakti.png"
        
        Scatter:
            do_translation:True
            size_hint_y:None
            height:700
            do_rotation:True
            do_scale:True
            Image:
                source:"/storage/emulated/0/Documents/Bhakti App/bhakti.png"             
